### ISSUE TITLE
Error when running lighthouse

### ISSUE THREAD

**Issue by cheripai** [emgram769/lighthouse#1]
This is what happens. I'm not sure if I did anything incorrectly

$ lighthouse | sh
Couldn't execute file.
Failed to spawn piped process.
Error in spawned cmd.

**Comment by emgram769** [comment]
That means you probably didn't run `make config` or lighthouse doesn't have permissions to run the file refered to by `cmd` in your `lighthouserc`.  If you believe the config file exists (`~/.config/lighthouse/lighthouserc`), try `chmod +x ~/.config/lighthouse/cmd`

**Comment by cheripai** [comment]
Ah yes. cmd had to be executable, thanks!
