### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by lygaret** [emgram769/lighthouse#10]
Hey, this thing is really neat, thanks!

What's the license? I created a package for lighthouse on AUR (the Arch Linux user package repository), and I wasn't sure what to use as the license. I put down `unknown` for now, but I'd like to get that correct before too long.

Sorry about the onslaught tonight :smirk:

**Comment by emgram769** [comment]
it's MIT in the lighthouse.c file (just the text).  I'll add clarification to the header of lighthouse.c

**Comment by lygaret** [comment]
heh, I've been pagedn'ing over that without even seeing it all night... :stuck_out_tongue_closed_eyes: 

thanks for pointing it out. :) maybe consider adding a LICENSE file?

**Comment by emgram769** [comment]
I'm not sure how the license file will interact with keysyms.c (different authors, same license type).  I'll look into it in depth tomorrow, I'm not too informed on how licenses work.

**Comment by lygaret** [comment]
oh, no worries. thanks for being responsive tonight!
