### ISSUE TITLE
don't exit on backspace

### ISSUE THREAD

**Issue by phavx** [emgram769/lighthouse#16]
While trying this out, I entered a few strings to see how it's working, in between deleting input by repeatedly pressing backspace. When I pressed it once too often, lighthouse closed, which I didn't expect and is imho a bad choice.

Consider only closing on Escape?

**Comment by emgram769** [comment]
it was a choice, but you can add `backspace_exit=0` to your lighthouserc to get that the way you like it, now

**Comment by phavx** [comment]
Thanks
