### ISSUE TITLE
image filenames containing & -> crash

### ISSUE THREAD

**Issue by 0ion9** [emgram769/lighthouse#22]
Step 1. Modify the inner loop from default cmd handler to only include this single line `echo '{%It&.png% t|t}'`
Step 2. Point lighthouses config at this modified handler
Step 3. Run lighthous
Step 4. Type anything
Step 5. Segfault :)

This crash occurs regardless of whether the referenced image file actually exists.

**Comment by emgram769** [comment]
that is an illegal filename, right? shouldn't the & be escaped?

**Comment by 0ion9** [comment]
.. Why would the & be escaped? This isn't shell script and as far as I know, & has no special meaning to lighthouse, correct me if I'm wrong.

(On a Ext2/3/4 filesystem or BTRFS filesystem, all characters except NUL and / are valid. I easily created a file t&,png ,just by saving an image normally in GIMP)

**Comment by emgram769** [comment]
Ah, I understand.  I was going off of the restrictions on [wordexp](http://linux.die.net/man/3/wordexp).  I'll add that escaping is necessary to address files with special characters in the README.  You can test your example file with t\&.png

**Comment by 0ion9** [comment]
This now works without escaping, BTW, so the mention in the README of & as a character that needs to be escaped seems to be outdated (at least for cmd output)

**Comment by 0ion9** [comment]
Ah, nvm. I wasn't reading closely enough; it causes errors only as a filename, which is consistent with the readme.
(not that this stops the 'problematic' image from loading!)
