### ISSUE TITLE
naming conflicts

### ISSUE THREAD

**Issue by phavx** [emgram769/lighthouse#23]
Forgot the URL to this repo, to lazy to dig through git so I googled, turns out there are quite a few other project (also on github) which share the same name, f.e. these:

https://github.com/inlight-media/lighthouse-ios
https://github.com/almindor/lighthouse
https://github.com/vinumeris/lighthouse

Not that I care that much, but for easier googling a not so generic name could be helpful.

**Comment by emgram769** [comment]
any suggestions on name modification?

**Comment by phavx** [comment]
Mh, as it's somewhat related to things like spotlight, dmenu, rofi or alfred, you could either build on that (f.e. spotty, searchlight/searchlite, emenu, rofl, ...) or find something unique(no ideas here).

**Comment by emgram769** [comment]
I looked through some of the other lighthouse repos and none of them really do anything similar.  a quick search through github puts this as the second result, so it seems reasonable to leave it for now.

**Comment by phavx** [comment]
That those projects are different in their nature is kind of my point. "lighthouse" itself is already a common word, so just googling for it would give a lot of useless links and it doesn't get better if the name is shared by more projects.

I don't mind though, after all it's your code.

**Comment by emgram769** [comment]
yea, I see your point. I'd imagine that people might google "lighthouse launcher" or something to that extent.  I think the arch linux forums has that as the second result
