### ISSUE TITLE
Dropdown menu has no output [Help Request]

### ISSUE THREAD

**Issue by eamrhein** [emgram769/lighthouse#24]
Lighthouse is executing commands, but the dropdown is not displaying results.

I am running and building this on gentoo. The build was created without any errors and the config file seems fine.  The only conclusion I have is that either I am missing one of the required libraries, or that my path is somehow incorrect.  

![2015-02-17-000920_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1903468/6224985/535607ce-b639-11e4-9de7-bd84d98dc1ce.png)

**Comment by 0ion9** [comment]
.. The dropdown shows **one result** in your screenshot.
???

Are you sure you're not just generating extra newlines? Lighthouse reads up to the next newline to get the list of options.

**Comment by krypt-n** [comment]
You are using the example shell script "cmd". It just outputs "look!" followed by the input. To get some more features change

```
cmd=~/.config/lighthouse/cmd
```

in the lighthouserc file to

```
cmd=~/.config/lighthouse/cmd.py
```

And make sure that cmd.py is executable.
