### ISSUE TITLE
If `find` tries to search inside a directory that doesn't have permission to access the file search function does nothing

### ISSUE THREAD

**Issue by ludat** [emgram769/lighthouse#27]
The problem is that check_output raises an exception if the command returns a non success (!= 0) value `subprocess.check_output` will throw an `CalledProcessError` that is not catched never.

This could be solved by either catching the exception and reading the output.

``` python
try:
    find_out = subprocess.check_output(["find", "/path/I/cant/read", "-name", query])
except subprocess.CalledProcessError as e:
    find_out = e.output
```

or calling the command with a shell and adding an `; exit 0;` at the end

``` python
    find_out = subprocess.check_output("find /path/I/cant/read -name "+query+";exit 0", shell=True)
```

Also getting the default directory (or directories because `query` could be a list) on the config file would be really useful

**Comment by emgram769** [comment]
feel free to submit these things as pull requests (try + except seems cleaner. I can modify this in a couple hours as I am on mobile atm).  I should note that this is a script intended to be used with lighthouse, not a part of lighthouse itself.  the config file should not include anything related to this script.
