### ISSUE TITLE
Document dependencies in readme.txt

### ISSUE THREAD

**Issue by williballenthin** [emgram769/lighthouse#3]
Figuring out the dependencies is not a difficult step if you know what you're doing, but it still probably requires a little trial and error to get right. Might be nice to list dependencies for common distros in the readme.

I've found I needed the following for NixOS:
- nixos.pkgs.xlibs.libX11
- nixos.pkgs.xlibs.libxcb
- nixos.pkgs.xlibs.libxproto
- nixos.pkgs.cairo

There might be a few others related to basic C compilation, but I'll leave those as an exercise to the reader.

On Ubuntu 14.10, I _think_ these dependencies would be (untested):
- libx11-dev
- libx11-xcb-dev
- libcairo2-dev

**Comment by emgram769** [comment]
Thanks! added dependencies section to the readme
