### ISSUE TITLE
Characters not displayed 

### ISSUE THREAD

**Issue by aniruddhazalani** [emgram769/lighthouse#33]
Characters are not being displayed as I type them and the screen goes white.
![bug](https://cloud.githubusercontent.com/assets/2152888/6271746/dcc7d52c-b888-11e4-8746-a5b0a7cc1fe3.png)

![image](https://cloud.githubusercontent.com/assets/2152888/6271712/a1cffb2a-b888-11e4-923b-4e145585d77e.png)

**Comment by emgram769** [comment]
if you wouldn't mind could you try `make clean;make debug` and then running `./lighthouse` and pasting the output? thanks!

**Comment by aniruddhazalani** [comment]
My hotkey binding is Alt+C. So as soon as I type "ac" the box vanishes. Here is the screenshot. 

![image](https://cloud.githubusercontent.com/assets/2152888/6273720/9737cd00-b897-11e4-8eaa-d2b930059cde.png)

Here is the image after I type "c". 

![image](https://cloud.githubusercontent.com/assets/2152888/6273743/c1ecfcfa-b897-11e4-8f0c-74a133014f7c.png)

terminal output: 
:~/lighthouse/lighthouse$ ./lighthouse | bash 
find: `~': No such file or directory
bash: line 1: Found: command not found
bash: line 2: randr: command not found
bash: line 3: key:: command not found
bash: line 4: key:: command not found
bash: line 5: Recieved: command not found
bash: line 6: Recieved: command not found
bash: line 7: key:: command not found
bash: line 8: Recieved: command not found
bash: line 9: Recieved: command not found
bash: line 10: key:: command not found
bash: line 11: Recieved: command not found
bash: line 12: Recieved: command not found
bash: line 13: key:: command not found
bash: line 14: Recieved: command not found
bash: line 15: key:: command not found

**Comment by emgram769** [comment]
I've pushed an update to cmd.py that will fix the find error, but I don't think that is causing it to crash.  could you run it again but this time without piping lighthouse into bash?  `make debug` actually changes the stdout to be debug statements and bash is complaining about them

**Comment by kornholi** [comment]
This happens when some icons in the results are in svg format. The problem disappeared after converting them to bitmaps.

**Comment by emgram769** [comment]
seems to be resolved by kornholi's comment. closing, feel free to open enhancement request for svg support
