### ISSUE TITLE
Segmentation fault on Arch Linux

### ISSUE THREAD

**Issue by tekknolagi** [emgram769/lighthouse#36]
When I run lighthouse (either installed from AUR or from GitHub) I get a segmentation fault.

**Comment by emgram769** [comment]
could you explain how you ran it and what input you were using? also, could you run `make debug` and paste the output?

**Comment by tekknolagi** [comment]
Actually, it doesn't happen after a reboot. That's odd.

I ran just `lighthouse`, and `make debug` just compiles with no warnings or errors.

**Comment by emgram769** [comment]
interesting. perhaps the segfault has something to do with an environment variable.  do you recall setting anything to a non-standard value?

**Comment by tekknolagi** [comment]
Nope. This was a very clean install as of about an hour ago.

**Comment by tekknolagi** [comment]
I do get bash syntax errors after typing each character, though

**Comment by emgram769** [comment]
when you `make debug` it modifies standard out to include debug statements (which bash will likely throw errors about). `make clean; make` to resolve this

**Comment by tekknolagi** [comment]
Even without piping to a shell?

**Comment by emgram769** [comment]
oh hmm... what are the errors?

**Comment by tekknolagi** [comment]
My VM is down right now, but something about mismatched quotes.

**Comment by emgram769** [comment]
closing due to lack of response. try the latest version and feel free to reopen if the problem persists
