### ISSUE TITLE
get_xdg_cmd doesn't return an entry 

### ISSUE THREAD

**Issue by m3rcuriel** [emgram769/lighthouse#37]
For some reason, with the default cmd.py, I'm unable to get .desktop files. I tried some primitive debugging on the code, and concluded that get_xdg_cmd never returns properly. Yes, I have the compgen fix.

**Comment by emgram769** [comment]
`get_xdg_cmd` silently handles not having all the packages installed. are you sure you have `pyxdg` installed on your system?

**Comment by m3rcuriel** [comment]
I ran through `get_xdg_cmd` in the Python shell and it didn't seem to fail. How do you recommend logging - I'll try to debug it myself.

**Comment by emgram769** [comment]
I'd test to see if it is catching an error and returning on line `97` or breaking out of the function on lines `130` or `134`

**Comment by m3rcuriel** [comment]
Aw shit I'm sorry - I had it for python3 and not python2. Now I have icons! They're too big, but they're there!

Also, I'd love to help work on this project - anything you need done?

**Comment by emgram769** [comment]
yea they're too big for me too, perhaps you could work on finding a good way to resize them? (either by adding code to resize images in lighthouse.c or just generating temporary files of the appropriate size in cmd.py)
