### ISSUE TITLE
Display glitch when embedded image is animated gif

### ISSUE THREAD

**Issue by 0ion9** [emgram769/lighthouse#40]
1. Use the following cmd handler
2. Save the following image as /tmp/test.gif
3. Launch lighthouse
4. Type 'foo'. Output and theming is normal.
5. Delete foo, type 'test'
6. Display stops updating. Logic appears to continue normally -- eg. hitting backspace 5 times causes lighthouse to exit (deleted all characters from the input, and then one more).

cmd handler:

```
#!/usr/bin/env bash

while read L; do
  if [ "$L" = "test" ]; then
    echo "{%I/tmp/test.gif% $L|$L}"
  else
    echo "{look! $L|$L}"
  fi
done
```

Image:

![test](https://cloud.githubusercontent.com/assets/115782/6707892/4f7b9d00-cdbb-11e4-8227-15b00d348d9e.gif)

**Comment by 0ion9** [comment]
Actually, a little further testing reveals it also occurs with non-animated gifs. Replacing test.gif with this:

![test](https://cloud.githubusercontent.com/assets/115782/6707960/f8476ce8-cdbb-11e4-8fb6-392738685479.gif)

still triggers the bug.

**Comment by emgram769** [comment]
whoops I did not specify that PNG image types are currently required.  I've since updated the readme.  I have yet to figure out a good way to get gifs to load with cairo.
