### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Caneehdian** [emgram769/lighthouse#45]
find: `/home/nick/.gvfs': Permission denied
find:`/home/nick/.cache/unity': Permission denied
find: `/home/nick/.cache/gvfs-burn': Permission denied
find:`/home/nick/.cache/dconf': Permission denied

**Comment by 0ion9** [comment]
.. what user is your cmd script running as? And what permissions do the specified directories have?

**Comment by emgram769** [comment]
closing due to lack of response
