### ISSUE TITLE
-c option causes error with valid config

### ISSUE THREAD

**Issue by david-morris** [emgram769/lighthouse#57]
Hi, I tried running `lighthouse -c` on my working config (~/.config/lighthouse/lighthouserc), at which point it dies before opening the prompt window.  When I invoke lighthouse without arguments, it functions as intended.  Dump:
% lighthouse -c lighthouserccopy                                        ~/.config/lighthouse
**\* Error in `lighthouse': munmap_chunk(): invalid pointer: 0x00007fff6a31153e ***
======= Backtrace: =========
/lib64/libc.so.6(+0x72bef)[0x7f64ed647bef]
/lib64/libc.so.6(+0x7803e)[0x7f64ed64d03e]
lighthouse[0x402dea]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f64ed5f6aa5]
lighthouse[0x403fb6]
======= Memory map: ========
00400000-00407000 r-xp 00000000 08:03 3947097                            /opt/bin/lighthouse
00606000-00607000 r--p 00006000 08:03 3947097                            /opt/bin/lighthouse
00607000-00608000 rw-p 00007000 08:03 3947097                            /opt/bin/lighthouse
00608000-0060d000 rw-p 00000000 00:00 0 
01901000-01922000 rw-p 00000000 00:00 0                                  [heap]
7f64e89f3000-7f64e8a08000 r-xp 00000000 08:03 5658509                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f64e8a08000-7f64e8c07000 ---p 00015000 08:03 5658509                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f64e8c07000-7f64e8c08000 r--p 00014000 08:03 5658509                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f64e8c08000-7f64e8c09000 rw-p 00015000 08:03 5658509                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f64e8c09000-7f64e8c0d000 r-xp 00000000 08:03 6860451                    /usr/lib64/libXxf86vm.so.1.0.0
7f64e8c0d000-7f64e8e0d000 ---p 00004000 08:03 6860451                    /usr/lib64/libXxf86vm.so.1.0.0
7f64e8e0d000-7f64e8e0e000 r--p 00004000 08:03 6860451                    /usr/lib64/libXxf86vm.so.1.0.0
7f64e8e0e000-7f64e8e0f000 rw-p 00005000 08:03 6860451                    /usr/lib64/libXxf86vm.so.1.0.0
7f64e8e0f000-7f64e8e10000 r-xp 00000000 08:03 6579544                    /usr/lib64/libxshmfence.so.1.0.0
7f64e8e10000-7f64e9010000 ---p 00001000 08:03 6579544                    /usr/lib64/libxshmfence.so.1.0.0
7f64e9010000-7f64e9011000 r--p 00001000 08:03 6579544                    /usr/lib64/libxshmfence.so.1.0.0
7f64e9011000-7f64e9012000 rw-p 00002000 08:03 6579544                    /usr/lib64/libxshmfence.so.1.0.0
7f64e9012000-7f64e9017000 r-xp 00000000 08:03 6982771                    /usr/lib64/libxcb-sync.so.1.0.0
7f64e9017000-7f64e9216000 ---p 00005000 08:03 6982771                    /usr/lib64/libxcb-sync.so.1.0.0
7f64e9216000-7f64e9217000 r--p 00004000 08:03 6982771                    /usr/lib64/libxcb-sync.so.1.0.0
7f64e9217000-7f64e9218000 rw-p 00005000 08:03 6982771                    /usr/lib64/libxcb-sync.so.1.0.0
7f64e9218000-7f64e921a000 r-xp 00000000 08:03 6982726                    /usr/lib64/libxcb-present.so.0.0.0
7f64e921a000-7f64e9419000 ---p 00002000 08:03 6982726                    /usr/lib64/libxcb-present.so.0.0.0
7f64e9419000-7f64e941a000 r--p 00001000 08:03 6982726                    /usr/lib64/libxcb-present.so.0.0.0
7f64e941a000-7f64e941b000 rw-p 00002000 08:03 6982726                    /usr/lib64/libxcb-present.so.0.0.0
7f64e941b000-7f64e941d000 r-xp 00000000 08:03 6982716                    /usr/lib64/libxcb-dri3.so.0.0.0
7f64e941d000-7f64e961c000 ---p 00002000 08:03 6982716                    /usr/lib64/libxcb-dri3.so.0.0.0
7f64e961c000-7f64e961d000 r--p 00001000 08:03 6982716                    /usr/lib64/libxcb-dri3.so.0.0.0
7f64e961d000-7f64e961e000 rw-p 00002000 08:03 6982716                    /usr/lib64/libxcb-dri3.so.0.0.0
7f64e961e000-7f64e9633000 r-xp 00000000 08:03 6982721                    /usr/lib64/libxcb-glx.so.0.0.0
7f64e9633000-7f64e9833000 ---p 00015000 08:03 6982721                    /usr/lib64/libxcb-glx.so.0.0.0
7f64e9833000-7f64e9835000 r--p 00015000 08:03 6982721                    /usr/lib64/libxcb-glx.so.0.0.0
7f64e9835000-7f64e9836000 rw-p 00017000 08:03 6982721                    /usr/lib64/libxcb-glx.so.0.0.0
7f64e9836000-7f64e983b000 r-xp 00000000 08:03 6856668                    /usr/lib64/libXfixes.so.3.1.0
7f64e983b000-7f64e9a3a000 ---p 00005000 08:03 6856668                    /usr/lib64/libXfixes.so.3.1.0
7f64e9a3a000-7f64e9a3b000 r--p 00004000 08:03 6856668                    /usr/lib64/libXfixes.so.3.1.0
7f64e9a3b000-7f64e9a3c000 rw-p 00005000 08:03 6856668                    /usr/lib64/libXfixes.so.3.1.0
7f64e9a3c000-7f64e9a3e000 r-xp 00000000 08:03 6856562                    /usr/lib64/libXdamage.so.1.1.0
7f64e9a3e000-7f64e9c3d000 ---p 00002000 08:03 6856562                    /usr/lib64/libXdamage.so.1.1.0
7f64e9c3d000-7f64e9c3e000 r--p 00001000 08:03 6856562                    /usr/lib64/libXdamage.so.1.1.0
7f64e9c3e000-7f64e9c3f000 rw-p 00002000 08:03 6856562                    /usr/lib64/libXdamage.so.1.1.0
7f64e9c3f000-7f64e9c4a000 r-xp 00000000 08:03 6850367                    /usr/lib64/libdrm.so.2.4.0
7f64e9c4a000-7f64e9e49000 ---p 0000b000 08:03 6850367                    /usr/lib64/libdrm.so.2.4.0
7f64e9e49000-7f64e9e4a000 r--p 0000a000 08:03 6850367                    /usr/lib64/libdrm.so.2.4.0
7f64e9e4a000-7f64e9e4b000 rw-p 0000b000 08:03 6850367                    /usr/lib64/libdrm.so.2.4.0
7f64e9e4b000-7f64e9e70000 r-xp 00000000 08:03 6990384                    /usr/lib64/libglapi.so.0.0.0
7f64e9e70000-7f64ea070000 ---p 00025000 08:03 6990384                    /usr/lib64/libglapi.so.0.0.0
7f64ea070000-7f64ea073000 r--p 00025000 08:03 6990384                    /usr/lib64/libglapi.so.0.0.0
7f64ea073000-7f64ea074000 rw-p 00028000 08:03 6990384                    /usr/lib64/libglapi.so.0.0.0
7f64ea074000-7f64ea075000 rw-p 00000000 00:00 0 
7f64ea075000-7f64ea080000 r-xp 00000000 08:03 6990332                    /usr/lib64/libgbm.so.1.0.0
7f64ea080000-7f64ea280000 ---p 0000b000 08:03 6990332                    /usr/lib64/libgbm.so.1.0.0
7f64ea280000-7f64ea281000 r--p 0000b000 08:03 6990332                    /usr/lib64/libgbm.so.1.0.0
7f64ea281000-7f64ea282000 rw-p 0000c000 08:03 6990332                    /usr/lib64/libgbm.so.1.0.0
7f64ea282000-7f64ea284000 r-xp 00000000 08:03 6982756                    /usr/lib64/libxcb-shape.so.0.0.0
7f64ea284000-7f64ea484000 ---p 00002000 08:03 6982756                    /usr/lib64/libxcb-shape.so.0.0.0
7f64ea484000-7f64ea485000 r--p 00002000 08:03 6982756                    /usr/lib64/libxcb-shape.so.0.0.0
7f64ea485000-7f64ea486000 rw-p 00003000 08:03 6982756                    /usr/lib64/libxcb-shape.so.0.0.0
7f64ea486000-7f64ea48c000 r-xp 00000000 08:03 6982776                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f64ea48c000-7f64ea68b000 ---p 00006000 08:03 6982776                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f64ea68b000-7f64ea68c000 r--p 00005000 08:03 6982776                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f64ea68c000-7f64ea68d000 rw-p 00006000 08:03 6982776                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f64ea68d000-7f64ea690000 r-xp 00000000 08:03 6982706                    /usr/lib64/libxcb-dri2.so.0.0.0
7f64ea690000-7f64ea890000 ---p 00003000 08:03 6982706                    /usr/lib64/libxcb-dri2.so.0.0.0
7f64ea890000-7f64ea891000 r--p 00003000 08:03 6982706                    /usr/lib64/libxcb-dri2.so.0.0.0
7f64ea891000-7f64ea892000 rw-p 00004000 08:03 6982706                    /usr/lib64/libxcb-dri2.so.0.0.0
7f64ea892000-7f64ea893000 r-xp 00000000 08:03 6984146                    /usr/lib64/libX11-xcb.so.1.0.0
7f64ea893000-7f64eaa92000 ---p 00001000 08:03 6984146                    /usr/lib64/libX11-xcb.so.1.0.0
7f64eaa92000-7f64eaa93000 r--p 00000000 08:03 6984146                    /usr/lib64/libX11-xcb.so.1.0.0
7f64eaa93000-7f64eaa94000 rw-p 00001000 08:03 6984146                    /usr/lib64/libX11-xcb.so.1.0.0
7f64eaa94000-7f64eaaa3000 r-xp 00000000 08:03 6052499                    /lib64/libbz2.so.1.0.6
7f64eaaa3000-7f64eaca2000 ---p 0000f000 08:03 6052499                    /lib64/libbz2.so.1.0.6
7f64eaca2000-7f64eaca3000 r--p 0000e000 08:03 6052499                    /lib64/libbz2.so.1.0.6
7f64eaca3000-7f64eaca4000 rw-p 0000f000 08:03 6052499                    /lib64/libbz2.so.1.0.6
7f64eaca4000-7f64eaccb000 r-xp 00000000 08:03 7099712                    /usr/lib64/libexpat.so.1.6.0
7f64eaccb000-7f64eaecb000 ---p 00027000 08:03 7099712                    /usr/lib64/libexpat.so.1.6.0
7f64eaecb000-7f64eaecd000 r--p 00027000 08:03 7099712                    /usr/lib64/libexpat.so.1.6.0
7f64eaecd000-7f64eaece000 rw-p 00029000 08:03 7099712                    /usr/lib64/libexpat.so.1.6.0
7f64eaece000-7f64eafcd000 r-xp 00000000 08:03 6870188                    /lib64/libm-2.20.so
7f64eafcd000-7f64eb1cc000 ---p 000ff000 08:03 6870188                    /lib64/libm-2.20.so
7f64eb1cc000-7f64eb1cd000 r--p 000fe000 08:03 6870188                    /lib64/libm-2.20.so
7f64eb1cd000-7f64eb1ce000 rw-p 000ff000 08:03 6870188                    /lib64/libm-2.20.so
7f64eb1ce000-7f64eb1d5000 r-xp 00000000 08:03 6871773                    /lib64/librt-2.20.so
7f64eb1d5000-7f64eb3d4000 ---p 00007000 08:03 6871773                    /lib64/librt-2.20.so
7f64eb3d4000-7f64eb3d5000 r--p 00006000 08:03 6871773                    /lib64/librt-2.20.so
7f64eb3d5000-7f64eb3d6000 rw-p 00007000 08:03 6871773                    /lib64/librt-2.20.so
7f64eb3d6000-7f64eb462000 r-xp 00000000 08:03 6990324                    /usr/lib64/opengl/xorg-x11/lib/libGL.so.1.2.0
7f64eb462000-7f64eb661000 ---p 0008c000 08:03 6990324                    /usr/lib64/opengl/xorg-x11/lib/libGL.so.1.2.0
7f64eb661000-7f64eb664000 r--p 0008b000 08:03 6990324                    /usr/lib64/opengl/xorg-x11/lib/libGL.so.1.2.0
7f64eb664000-7f64eb665000 rw-p 0008e000 08:03 6990324                    /usr/lib64/opengl/xorg-x11/lib/libGL.so.1.2.0
7f64eb665000-7f64eb666000 rw-p 00000000 00:00 0 
7f64eb666000-7f64eb67b000 r-xp 00000000 08:03 6574856                    /lib64/libz.so.1.2.8
7f64eb67b000-7f64eb87a000 ---p 00015000 08:03 6574856                    /lib64/libz.so.1.2.8
7f64eb87a000-7f64eb87b000 r--p 00014000 08:03 6574856                    /lib64/libz.so.1.2.8
7f64eb87b000-7f64eb87c000 rw-p 00015000 08:03 6574856                    /lib64/libz.so.1.2.8
7f64eb87c000-7f64eb88d000 r-xp 00000000 08:03 6860458                    /usr/lib64/libXext.so.6.4.0
7f64eb88d000-7f64eba8c000 ---p 00011000 08:03 6860458                    /usr/lib64/libXext.so.6.4.0
7f64eba8c000-7f64eba8d000 r--p 00010000 08:03 6860458                    /usr/lib64/libXext.so.6.4.0
7f64eba8d000-7f64eba8e000 rw-p 00011000 08:03 6860458                    /usr/lib64/libXext.so.6.4.0
7f64eba8e000-7f64ebbc3000 r-xp 00000000 08:03 6984144                    /usr/lib64/libX11.so.6.3.0
7f64ebbc3000-7f64ebdc3000 ---p 00135000 08:03 6984144                    /usr/lib64/libX11.so.6.3.0
7f64ebdc3000-7f64ebdc4000 r--p 00135000 08:03 6984144                    /usr/lib64/libX11.so.6.3.0
7f64ebdc4000-7f64ebdc9000 rw-p 00136000 08:03 6984144                    /usr/lib64/libX11.so.6.3.0
7f64ebdc9000-7f64ebdd2000 r-xp 00000000 08:03 6859542                    /usr/lib64/libXrender.so.1.3.0
7f64ebdd2000-7f64ebfd1000 ---p 00009000 08:03 6859542                    /usr/lib64/libXrender.so.1.3.0
7f64ebfd1000-7f64ebfd2000 r--p 00008000 08:03 6859542                    /usr/lib64/libXrender.so.1.3.0
7f64ebfd2000-7f64ebfd3000 rw-p 00009000 08:03 6859542                    /usr/lib64/libXrender.so.1.3.0
7f64ebfd3000-7f64ebfdb000 r-xp 00000000 08:03 6982746                    /usr/lib64/libxcb-render.so.0.0.0
7f64ebfdb000-7f64ec1db000 ---p 00008000 08:03 6982746                    /usr/lib64/libxcb-render.so.0.0.0
7f64ec1db000-7f64ec1dc000 r--p 00008000 08:03 6982746                    /usr/lib64/libxcb-render.so.0.0.0
7f64ec1dc000-7f64ec1dd000 rw-p 00009000 08:03 6982746                    /usr/lib64/libxcb-render.so.0.0.0
7f64ec1dd000-7f64ec1df000 r-xp 00000000 08:03 6982761                    /usr/lib64/libxcb-shm.so.0.0.0
7f64ec1df000-7f64ec3de000 ---p 00002000 08:03 6982761                    /usr/lib64/libxcb-shm.so.0.0.0
7f64ec3de000-7f64ec3df000 r--p 00001000 08:03 6982761                    /usr/lib64/libxcb-shm.so.0.0.0
7f64ec3df000-7f64ec3e0000 rw-p 00002000 08:03 6982761                    /usr/lib64/libxcb-shm.so.0.0.0
7f64ec3e0000-7f64ec414000 r-xp 00000000 08:03 6574526                    /usr/lib64/libpng16.so.16.16.0
7f64ec414000-7f64ec613000 ---p 00034000 08:03 6574526                    /usr/lib64/libpng16.so.16.16.0
7f64ec613000-7f64ec614000 r--p 00033000 08:03 6574526                    /usr/lib64/libpng16.so.16.16.0
7f64ec614000-7f64ec615000 rw-p 00034000 08:03 6574526                    /usr/lib64/libpng16.so.16.16.0
7f64ec615000-7f64ec617000 r-xp 00000000 08:03 6871233                    /lib64/libdl-2.20.so
7f64ec617000-7f64ec817000 ---p 00002000 08:03 6871233                    /lib64/libdl-2.20.so
7f64ec817000-7f64ec818000 r--p 00002000 08:03 6871233                    /lib64/libdl-2.20.so
7f64ec818000-7f64ec819000 rw-p 00003000 08:03 6871233                    /lib64/libdl-2.20.so
7f64ec819000-7f64ec83c000 r-xp 00000000 08:03 6990338                    /usr/lib64/opengl/xorg-x11/lib/libEGL.so.1.0.0
7f64ec83c000-7f64eca3c000 ---p 00023000 08:03 6990338                    /usr/lib64/opengl/xorg-x11/lib/libEGL.so.1.0.0
7f64eca3c000-7f64eca3d000 r--p 00023000 08:03 6990338                    /usr/lib64/opengl/xorg-x11/lib/libEGL.so.1.0.0
7f64eca3d000-7f64eca3e000 rw-p 00024000 08:03 6990338                    /usr/lib64/opengl/xorg-x11/lib/libEGL.so.1.0.0
7f64eca3e000-7f64ecadf000 r-xp 00000000 08:03 6702054                    /usr/lib64/libfreetype.so.6.11.4
7f64ecadf000-7f64eccde000 ---p 000a1000 08:03 6702054                    /usr/lib64/libfreetype.so.6.11.4
7f64eccde000-7f64ecce4000 r--p 000a0000 08:03 6702054                    /usr/lib64/libfreetype.so.6.11.4
7f64ecce4000-7f64ecce5000 rw-p 000a6000 08:03 6702054                    /usr/lib64/libfreetype.so.6.11.4
7f64ecce5000-7f64ecd20000 r-xp 00000000 08:03 6844373                    /usr/lib64/libfontconfig.so.1.8.0
7f64ecd20000-7f64ecf1f000 ---p 0003b000 08:03 6844373                    /usr/lib64/libfontconfig.so.1.8.0
7f64ecf1f000-7f64ecf21000 r--p 0003a000 08:03 6844373                    /usr/lib64/libfontconfig.so.1.8.0
7f64ecf21000-7f64ecf22000 rw-p 0003c000 08:03 6844373                    /usr/lib64/libfontconfig.so.1.8.0
7f64ecf22000-7f64ecfc3000 r-xp 00000000 08:03 6574572                    /usr/lib64/libpixman-1.so.0.32.6
7f64ecfc3000-7f64ed1c3000 ---p 000a1000 08:03 6574572                    /usr/lib64/libpixman-1.so.0.32.6
7f64ed1c3000-7f64ed1ca000 r--p 000a1000 08:03 6574572                    /usr/lib64/libpixman-1.so.0.32.6
7f64ed1ca000-7f64ed1cb000 rw-p 000a8000 08:03 6574572                    /usr/lib64/libpixman-1.so.0.32.6
7f64ed1cb000-7f64ed1d0000 r-xp 00000000 08:03 6579420                    /usr/lib64/libXdmcp.so.6.0.0
7f64ed1d0000-7f64ed3cf000 ---p 00005000 08:03 6579420                    /usr/lib64/libXdmcp.so.6.0.0
7f64ed3cf000-7f64ed3d0000 r--p 00004000 08:03 6579420                    /usr/lib64/libXdmcp.so.6.0.0
7f64ed3d0000-7f64ed3d1000 rw-p 00005000 08:03 6579420                    /usr/lib64/libXdmcp.so.6.0.0
7f64ed3d1000-7f64ed3d3000 r-xp 00000000 08:03 6579073                    /usr/lib64/libXau.so.6.0.0
7f64ed3d3000-7f64ed5d3000 ---p 00002000 08:03 6579073                    /usr/lib64/libXau.so.6.0.0
7f64ed5d3000-7f64ed5d4000 r--p 00002000 08:03 6579073                    /usr/lib64/libXau.so.6.0.0
7f64ed5d4000-7f64ed5d5000 rw-p 00003000 08:03 6579073                    /usr/lib64/libXau.so.6.0.0
7f64ed5d5000-7f64ed763000 r-xp 00000000 08:03 6870213                    /lib64/libc-2.20.so
7f64ed763000-7f64ed963000 ---p 0018e000 08:03 6870213                    /lib64/libc-2.20.so
7f64ed963000-7f64ed967000 r--p 0018e000 08:03 6870213                    /lib64/libc-2.20.so
7f64ed967000-7f64ed969000 rw-p 00192000 08:03 6870213                    /lib64/libc-2.20.so
7f64ed969000-7f64ed96d000 rw-p 00000000 00:00 0 
7f64ed96d000-7f64ed983000 r-xp 00000000 08:03 6871218                    /lib64/libpthread-2.20.so
7f64ed983000-7f64edb82000 ---p 00016000 08:03 6871218                    /lib64/libpthread-2.20.so
7f64edb82000-7f64edb83000 r--p 00015000 08:03 6871218                    /lib64/libpthread-2.20.so
7f64edb83000-7f64edb84000 rw-p 00016000 08:03 6871218                    /lib64/libpthread-2.20.so
7f64edb84000-7f64edb88000 rw-p 00000000 00:00 0 
7f64edb88000-7f64edca5000 r-xp 00000000 08:03 6867289                    /usr/lib64/libcairo.so.2.11400.2
7f64edca5000-7f64edea4000 ---p 0011d000 08:03 6867289                    /usr/lib64/libcairo.so.2.11400.2
7f64edea4000-7f64edea7000 r--p 0011c000 08:03 6867289                    /usr/lib64/libcairo.so.2.11400.2
7f64edea7000-7f64edea9000 rw-p 0011f000 08:03 6867289                    /usr/lib64/libcairo.so.2.11400.2
7f64edea9000-7f64edeaa000 rw-p 00000000 00:00 0 
7f64edeaa000-7f64edeb6000 r-xp 00000000 08:03 6982731                    /usr/lib64/libxcb-randr.so.0.1.0
7f64edeb6000-7f64ee0b6000 ---p 0000c000 08:03 6982731                    /usr/lib64/libxcb-randr.so.0.1.0
7f64ee0b6000-7f64ee0b7000 r--p 0000c000 08:03 6982731                    /usr/lib64/libxcb-randr.so.0.1.0
7f64ee0b7000-7f64ee0b8000 rw-p 0000d000 08:03 6982731                    /usr/lib64/libxcb-randr.so.0.1.0
7f64ee0b8000-7f64ee0ba000 r-xp 00000000 08:03 6982781                    /usr/lib64/libxcb-xinerama.so.0.0.0
7f64ee0ba000-7f64ee2b9000 ---p 00002000 08:03 6982781                    /usr/lib64/libxcb-xinerama.so.0.0.0
7f64ee2b9000-7f64ee2ba000 r--p 00001000 08:03 6982781                    /usr/lib64/libxcb-xinerama.so.0.0.0
7f64ee2ba000-7f64ee2bb000 rw-p 00002000 08:03 6982781                    /usr/lib64/libxcb-xinerama.so.0.0.0
7f64ee2bb000-7f64ee2d4000 r-xp 00000000 08:03 6982791                    /usr/lib64/libxcb-xkb.so.1.0.0
7f64ee2d4000-7f64ee4d4000 ---p 00019000 08:03 6982791                    /usr/lib64/libxcb-xkb.so.1.0.0
7f64ee4d4000-7f64ee4d5000 r--p 00019000 08:03 6982791                    /usr/lib64/libxcb-xkb.so.1.0.0
7f64ee4d5000-7f64ee4d6000 rw-p 0001a000 08:03 6982791                    /usr/lib64/libxcb-xkb.so.1.0.0
7f64ee4d6000-7f64ee4f4000 r-xp 00000000 08:03 6982660                    /usr/lib64/libxcb.so.1.1.0
7f64ee4f4000-7f64ee6f4000 ---p 0001e000 08:03 6982660                    /usr/lib64/libxcb.so.1.1.0
7f64ee6f4000-7f64ee6f5000 r--p 0001e000 08:03 6982660                    /usr/lib64/libxcb.so.1.1.0
7f64ee6f5000-7f64ee6f6000 rw-p 0001f000 08:03 6982660                    /usr/lib64/libxcb.so.1.1.0
7f64ee6f6000-7f64ee717000 r-xp 00000000 08:03 6871214                    /lib64/ld-2.20.so
7f64ee8d7000-7f64ee8ea000 rw-p 00000000 00:00 0 
7f64ee914000-7f64ee916000 rw-p 00000000 00:00 0 
7f64ee916000-7f64ee917000 r--p 00020000 08:03 6871214                    /lib64/ld-2.20.so
7f64ee917000-7f64ee918000 rw-p 00021000 08:03 6871214                    /lib64/ld-2.20.so
7f64ee918000-7f64ee919000 rw-p 00000000 00:00 0 
7fff6a2f1000-7fff6a312000 rw-p 00000000 00:00 0                          [stack]
7fff6a3fc000-7fff6a3fe000 r--p 00000000 00:00 0                          [vvar]
7fff6a3fe000-7fff6a400000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
[1]    14498 abort      lighthouse -c lighthouserccopy

**Comment by emgram769** [comment]
hopefully this works, feel free to reopen if not
