### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by ix5** [emgram769/lighthouse#86]
The `lighthouse-git` package in the AUR is out of date. @emgram769 are you 'the_lf'(the maintainer)?

The `build()` function should be changed from `make` to `make lighthouse`. Simple fix.

**Comment by emgram769** [comment]
I am unfortunately not the maintainer of the AUR package.  I'll leave this open for visibility.

**Comment by bebehei** [comment]
This bug is fixed and can be closed:

https://aur.archlinux.org/cgit/aur.git/commit/?h=lighthouse-git&id=081c885dfe303a7545f270bed9f40a5c9cda332c

**Comment by ix5** [comment]
Closed, thanks.
